### ISSUE TITLE
UPDATE IN CONTRIBUTION.md FILE 

### ISSUE THREAD

**Issue by akrish4** [thinktocode/COVID-19-Tracker#1]
Hi @thinktocode 
This projecct or app looks really nice 
But I found this repository contribution file is not that much nice as the app's beauty 
Kindly assign me this issue , I would like to work on the contributing file ,
I would like to contribute a well better contribution file

**Comment by thinktocode** [comment]
Hi, @akrish4 Nice to meet you. I have assigned the issue to you. Let me know if you need any help buddy. Good Luck!

**Comment by akrish4** [comment]
> Hi, @akrish4 Nice to meet you. I have assigned the issue to you. Let me know if you need any help buddy. Good Luck!

Thank you @thinktocode 
Since this project registered under DWOC 
Kindly add the tags ie `DWOC` tag and `Level` tag ( Level-1 or Level-2 or Level-3)

**Comment by akrish4** [comment]
@thinktocode  Its `Level-1` or `Level-2` tags , not `Level` 
KIndly update it.

**Comment by thinktocode** [comment]
How to do that?

**Comment by akrish4** [comment]
> How to do that?

You need to remove the `Level` tag and add `Level-1` or `level-2` tag

**Comment by thinktocode** [comment]
Can you send the details for Project Owners dude? I haven't got any guidelines or instructions, do you have any idea abt it?

**Comment by akrish4** [comment]
> Can you send the details for Project Owners dude? I haven't got any guidelines or instructions, do you have any idea abt it?

yes , haven't you joined the discord ? there they have given all details and all rules for project maintainers and participants

**Comment by thinktocode** [comment]
Oh! I was actually busy. I'll join right now, give me some time

**Comment by akrish4** [comment]
> Oh! I was actually busy. I'll join right now, give me some time

yeah sure

**Comment by thinktocode** [comment]
I joined the discord but I cant found the guidelines.

**Comment by akrish4** [comment]
Hi @thinktocode 
I have worked on it

**Comment by akrish4** [comment]
#3  PR
