### ISSUE TITLE
README FILE BADGES IMPROVE 

### ISSUE THREAD

**Issue by akrish4** [thinktocode/COVID-19-Tracker#13]
Hi @thinktocode 
There are only 2 badges or shields in the readme file , Kindly assign me if you would like to see more badges in it 

![readme1](https://user-images.githubusercontent.com/61831021/103935183-35635a00-514c-11eb-8e51-78c018c4f188.PNG)

**Comment by thinktocode** [comment]
Alright, but keep relevant badges.  Use this style for badges.

https://img.shields.io/badge/style-for--the--badge-green?logo=appveyor&style=for-the-badge

**Comment by akrish4** [comment]
> Alright, but keep relevant badges. Use this style for badges.
> 
> https://img.shields.io/badge/style-for--the--badge-green?logo=appveyor&style=for-the-badge

sure @thinktocode

**Comment by akrish4** [comment]
Hi @thinktocode 
Kindly do check and merge it 
Kindly do add the same labels to the pr aswell 
#14
