### ISSUE TITLE
Bug in Dark mode Switch 

### ISSUE THREAD

**Issue by sharmaumang001** [thinktocode/COVID-19-Tracker#18]
The application switches from Dark-Mode to light mode when we tap the text (Dark mode ), But when the user just uses the toggle button it does not perform any action.

Please assign this to me.

**Comment by thinktocode** [comment]
Hey @sharmaumang001 Are you still working on it?

**Comment by sharmaumang001** [comment]
I solved it nearly, a bug still there. But I got busy with something else after that. Sorry for informing late
Please assign it to someone else, for now.

**Comment by thinktocode** [comment]
@sharmaumang001 no issue. No one wants to work on this for now. So you can continue working on it
