### ISSUE TITLE
Update Contributing.md File

### ISSUE THREAD

**Issue by bhavesh1129** [thinktocode/COVID-19-Tracker#2]
Hey @thinktocode!
I had checkout your project and it is so good but as I can see you haven't added anything in your contributing.md file so I want to take up this issue and make your contributing.md file awesome as your project is.

Thankyou!

**Comment by thinktocode** [comment]
Hi, @bhavesh1129. Someone has already updated the Contribution file and made the PR. So you can pick anything else to change. Good luck
