### ISSUE TITLE
Add Contibutors.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [thinktocode/COVID-19-Tracker#4]
Hai,
I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md.I would also add a link to Code of Conduct file in README.md

**Comment by muthuannamalai12** [comment]
I would to work on this issue as a part of DWOC.Kindly assign it to me

**Comment by thinktocode** [comment]
@muthuannamalai12 Good Luck!

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
