### ISSUE TITLE
Bug fix in Pie chart data presentation.

### ISSUE THREAD

**Issue by thinktocode** [thinktocode/COVID-19-Tracker#7]
Greetings!

The app presents Covid data of India using Pie Chart. But there are some bugs in it. The text in pie needs to be aligned properly.

**Comment by Anu-MADMAX** [comment]
Interested in this issue. Let me know how i can help

**Comment by thinktocode** [comment]
Hey! @Anu-MADMAX 
![Screenshot_20210104-101402_Covid-19 Tracker](https://user-images.githubusercontent.com/73512577/103501928-b33a1380-4e75-11eb-96ce-c55b5195999b.jpg)

![Screenshot_20210104-101402_Covid-19 Tracker](https://user-images.githubusercontent.com/73512577/103502021-f7c5af00-4e75-11eb-867a-87019e75c69c.jpg)

As you can see in the screenshot above, the text is coming on the pie itself. 
We can make the text come at a side rather than coming on the pie. I hope you got it?
If you wanna work on it then reply with a Yes so that I can assign you the issue.

**Comment by Anu-MADMAX** [comment]
Yes, I want to work on it. But i would need your guidance to go about the
issue

**Comment by thinktocode** [comment]
Yeah, I can help you but I think guidance stuff needs to be given by mentors. I'm the project maintainer.
Have you joined the discord yet?
There was one mentor for this project.

**Comment by Anu-MADMAX** [comment]
Ok , I will message on the discord then

**Comment by thinktocode** [comment]
@Anu-MADMAX Should I assign you the issue?

**Comment by Anu-MADMAX** [comment]
Yeah, assign it to me. 👍

**Comment by Amit366** [comment]
Ok I will give it a try

**Comment by thinktocode** [comment]
Good Luck! @Amit366

**Comment by thinktocode** [comment]
Bug has been resolved.
